# -*- coding: utf-8 -*-
"""AULA 06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-D7jRSaRDOrrfDz3C82y8JNKTEK3cx0Q
"""

# numero_inteiro = 10.0
# print(type('numero_inteiro'))
# real = bool(numero_inteiro)
# print(type(numero_inteiro))

# lista = [1,2,3,4,5,6,7,8,9,10,11,12]

# minimo_da_minha_lista = min(lista)
# maximo_da_minha_lista = max(lista)
# organizar = sorted(lista)
# soma = sum(lista)
# print('minimo - ',minimo_da_minha_lista)
# print('maximo - ',maximo_da_minha_lista)
# print('lista organizado - ',organizar)
# print('soma da minha lista - ',soma)

# 1 Imprima uma mensagem de boas-vindas na tela.
print('Olá tudo bem ?')

# 2 Declare uma variável booleana verdadeiro
n = 10.0
real = bool(n)
print(real)
print(type(real))

# 3 Imprima o resultado da multiplicação de dois números decimais de sua escolha
n1 = 10.6
n2 = 15.6
print(n1*n2)

# 4 Imprima o resultado da divisão de dois números inteiros
# de sua escolha.
n1 = 15
n2 = 5
divisao = n1 / n2
print(divisao)

# 5  Imprima o resultado da subtração de dois números inteiros de sua escolha
n1 = 1200
n2 = 3000
subtracao = n1 - n2
print(subtracao)

# 8 Declare uma variável numero e atribua um número inteiro. Em seguida,
# imprima o dobro desse número
numero = 20
print(numero*2)

# 9 Crie uma calculadora de soma com as ferramentas que vc já
#conhece(Use apenas input, print e variavel)

n1 = float(input('Digite um numero:'))
n2 = float(input('Digite um numero ao qual vc deseja multiplicar:'))
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)

#10 Crie um sistema de cadastro com as estruturas que vc já conhece(Use apenas input, print e variavel)
nome = input('Digite seu nome:')
idade = int(input('Digite sua idade :'))
profissao = input('digite sua profissão :')
print(nome)
print(idade)
print(profissao)
print('Usuario cadastrado com sucesso!')