# -*- coding: utf-8 -*-
"""Aula 7 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1joELf2r49K08kduOLG-yAGB0S_pbkwpB
"""

# Posso criar um módulo
# Posso usar algo que está pronto no python
# Existe um módulo chamado random == aleatório


3
# aleatorio = random.random()
# aleatorio2 = random.random()
# print(aleatorio,aleatorio2)

# aleatorio3 = random.randint(3,8)
# print(aleatorio3)

# aleatorio4 = random.randrange(4,15)
# print(aleatorio4)

import random

for n in range(1,4):
  meu_numero = int(input('>>'))
  numero_aleatorio = random.randint(1,5)
  if meu_numero == numero_aleatorio:
    print('Você ganhou! o numero é',numero_aleatorio )
    break
  else:
    print('Você errou feio! O numero é', numero_aleatorio)
    print('Voce gastou ', n, 'chances')
    if n == 3:
        print('Voce esgotou a quantidade de chances')

# ### **Atividade: Calculadora de Média de Notas**

# Crie um programa que permita ao usuário calcular a média de suas notas em diferentes disciplinas. O programa deve solicitar ao usuário que insira o número de disciplinas e, em seguida, pedir que insira as notas de cada disciplina. Depois de coletar todas as notas, o programa deve calcular e exibir a média geral.

# ### Passos para a implementação:

# 1. Solicite ao usuário que insira o número de disciplinas.
# 2. Use um loop para solicitar as notas de cada disciplina.
# 3. Calcule a média das notas.
# 4. Exiba a média geral ao usuário.
soma = 0
diciplinas = [1,2,3,4]
for n in diciplinas:
    nota = float(input('nota : '))
    soma = soma + nota
    media = soma/len(diciplinas)
print('A sua média é',media)

# 1. Solicite ao usuário que insira o número de disciplinas.
numero_dis = int(input('Digite o numero de disciplinas '))
soma = 0
# 2. Use um loop para solicitar as notas de cada disciplina.
for i in range(1,numero_dis):
    notas =  float(input(f'Digite a {i}º nota: '))
    soma = soma + notas
    # 3. Calcule a média das notas.
    media =  soma / len(range(1,numero_dis))
# 4. Exiba a média geral ao usuário.
print('Média: ',  media)

soma = 0

disciplinas = int(input('Digite qtd de disciplina :'))

for n in range(1,disciplinas):
    nota = int(input(f'digite a {n}° nota:'))
    soma = soma + nota
media = soma/len(range(1,disciplinas))
print('A sua média é',media)